#include "html_response.h"

const char *html_response =
    "HTTP/1.1 200 OK\r\n"
    "Content-Type: text/html\r\n\r\n"
    "<!DOCTYPE html>"
    "<html lang='pt-BR'>"
    "<head><meta charset='UTF-8'><title>Pico W - Joystick</title>"
    "<style>"
    "body{font-family:Arial;text-align:center;background:#111;color:#eee;}"
    "h1{margin-top:50px;}"
    "#data{margin-top:30px;font-size:1.2em;}"
    "</style></head>"
    "<body>"
    "<h1>Monitoramento - Joystick Pico W</h1>"
    "<div id='data'>"
    "X: <span id='x_val'>?</span><br>"
    "Y: <span id='y_val'>?</span><br>"
    "Direção: <span id='direction'>?</span><br>"
    "Botão 1: <span id='b1'>?</span><br>"
    "Botão 2: <span id='b2'>?</span><br>"
    "</div>"
    "<script>"
    "</script>"
    "</body></html>";