#include "html_response.h"

const char *html_response =
    "HTTP/1.1 200 OK\r\n"
    "Content-Type: text/html\r\n\r\n"
    "<!DOCTYPE html>"
    "<html lang='pt-BR'>"
    "<head><meta charset='UTF-8'><title>Monitoramento Sensores</title>"
    "<style>""</style></head>"
    "<body>"
    "<h1>Monitoramento Sensores</h1>"
    "<div id='data'>"
    "X: <span id='x_val'>?</span><br>"
    "Y: <span id='y_val'>?</span><br>"
    "Direção: <span id='direction'>?</span><br>"
    "Botão 1: <span id='b1'>?</span><br>"
    "Botão 2: <span id='b2'>?</span><br>"
    "Ultrassonico: <span id='ut'>?</span> cm<br>"
    "</div>"
    "<script>"
    "function atualizarDados() {"
    "  fetch('/data')"
    "    .then(res => res.json())"
    "    .then(data => {"
    "      document.getElementById('x_val').textContent = data.x;"
    "      document.getElementById('y_val').textContent = data.y;"
    "      document.getElementById('direction').textContent = data.direction;"
    "      document.getElementById('b1').textContent = data.button1;"
    "      document.getElementById('b2').textContent = data.button2;"
    "      document.getElementById('ut').textContent = data.ultra;"
    "    })"
    "    .catch(err => console.error('Erro ao buscar dados:', err));"
    "}"
    "setInterval(atualizarDados, 1000);"
    "atualizarDados();"
    "</script>"
    "</body></html>";
